name: 'esnupi.me Post Next Image'

on:
  workflow_dispatch:
  schedule:
    - cron: "50 * * * *"

jobs:
  post-next-image:
    name: Post Next Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 1
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /*
            !imagequeue

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Poast!
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          CURRENT_IMAGE=$(gh variable get LAST_IMAGE_NAME || echo "")
          if [ -z "$CURRENT_IMAGE" ]; then
            echo "Error: LAST_IMAGE_NAME variable is empty."
            exit 1
          fi
          mkdir -p imagequeue
          git sparse-checkout add "imagequeue/$CURRENT_IMAGE"
          git checkout "imagequeue/$CURRENT_IMAGE"
          export LAST_IMAGE_NAME="$CURRENT_IMAGE"
          echo "Current: $CURRENT_IMAGE"
          NEW_IMAGE=$(yarn --silent run start)
          if [ -n "$NEW_IMAGE" ] && [ "$NEW_IMAGE" != "$CURRENT_IMAGE" ]; then
            echo "Success. Setting next image to: $NEW_IMAGE"
            gh variable set LAST_IMAGE_NAME --body "$NEW_IMAGE"
          else
            echo "Error: Script failed to rotate image. (New: '$NEW_IMAGE')"
            exit 1
          fi
