name: 'esnupi.me Post Next Image'

on:
  workflow_dispatch:
  schedule:
    - cron: "50 * * * *"

jobs:
  post-next-image:
    name: Post Next Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 1
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            /*
            !imagequeue

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Poast!
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          IMAGE_LIST=$(gh variable get LAST_IMAGE_NAME || echo "")
          mkdir -p imagequeue
          if [ -n "$IMAGE_LIST" ]; then
            IFS=',' read -ra ADDR <<< "$IMAGE_LIST"
            for img in "${ADDR[@]}"; do
              img_clean=$(echo "$img" | xargs)
              if [ -n "$img_clean" ]; then
                echo "Fetching: $img_clean"
                git sparse-checkout add "imagequeue/$img_clean"
                git checkout "imagequeue/$img_clean"
              fi
            done
          fi
          export LAST_IMAGE_NAME="$IMAGE_LIST"
          NEW_LIST=$(yarn --silent run start | tail -n 1 | xargs)
          if [ -n "$NEW_LIST" ] && [ "$NEW_LIST" != "$IMAGE_LIST" ]; then
             echo "Updating image history for next run."
             gh variable set LAST_IMAGE_NAME --body "$NEW_LIST"
          else
             echo "FATAL: history list not updated."
             exit 1
          fi